language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
  - PLONE_VERSION=4
  - PLONE_VERSION=5
matrix:
  allow_failures:
  - env: PLONE_VERSION=5
install:
- sed -ie "s#test-4.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- pip install zc.buildout
- buildout -N -q -t 3
script:
- bin/test
- bin/code-analysis
